# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: (Apache-2.0 OR BSD-3-Clause)
version: 2.1

jobs:
  application:
    docker:
      - image: hseeberger/scala-sbt:11.0.2_2.12.8_1.2.8
    environment:
      - MAKEFLAGS: "-i"
    steps:
      - checkout
      - run:
          name: Install make
          command: apt-get update && apt-get install make
      - run:
          name: Build Application
          command: make build-app
  daml:
    docker:
      - image: digitalasset/daml-sdk:0.12.17-circleci-master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test Dar
          command: make test-dar
      - run:
          name: Build Dar
          command: make build-dar
      - run:
          name: Save test results
          command: |
            mkdir -pv ~/test-results/daml
            find . -type f -regex ".*/target/.*DarTests.xml" -exec cp {} ~/test-results/daml/ \;
      - store_test_results:
          path: ~/test-results

workflows:
  Build and test:
    jobs:
      - application
      - daml
