# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: (Apache-2.0 OR BSD-3-Clause)
version: 2.1

jobs:
  application:
    docker:
      - image: mozilla/sbt:latest
    environment:
      - MAKEFLAGS: "-i"
    steps:
      - checkout
      - run:
          name: Install make
          command: (apt-get update || apt-get update) && apt-get install make
      - run:
          name: Build Application
          command: make build-app
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) ci-build digitalasset_ex-structured-products master --logging.level.com.synopsys.integration=DEBUG --detect.notices.report=true --detect.report.timeout=600
  daml:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install DAML
          command: |
            curl -sSL https://get.daml.com/ | sh
            PATH=$PATH:/home/circleci/.daml/bin
            daml install project
      - run:
          name: Test Dar
          command: |
            PATH=$PATH:/home/circleci/.daml/bin
            make test-dar
      - run:
          name: Build Dar
          command: |
            PATH=$PATH:/home/circleci/.daml/bin
            make build-dar
      - run:
          name: Save test results
          command: |
            mkdir -pv ~/test-results/daml
            find . -type f -regex ".*/dist/.*DarTests.xml" -exec cp {} ~/test-results/daml/ \;
      - store_test_results:
          path: ~/test-results

workflows:
  Build and test:
    jobs:
      - daml
      - application:
            context: blackduck
